export const UPDATE_STEP = "UPDATE_STEP";
export const UPDATE_FORM_STATUS = "UPDATE_FORM_STATUS";
export const UPDATE_ROOMS_DATA = "UPDATE_ROOMS_DATA";
export const UPDATE_MOODS_DATA = "UPDATE_MOODS_DATA";
export const UPDATE_FURNITURES_DATA = "UPDATE_FURNITURES_DATA";
export const UPDATE_BRANDS_DATA = "UPDATE_BRANDS_DATA";
export const UPDATE_COLORS_DATA = "UPDATE_COLORS_DATA";
export const RESET_FORM = "RESET_FORM";
